// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AssetFile struct {
	ID           pgtype.UUID
	OriginalName string
	StoredName   string
	MimeType     string
	SizeBytes    int32
	PublicPath   string
	CreatedAt    pgtype.Timestamptz
}

type Group struct {
	ID        pgtype.UUID
	Name      string
	SortOrder int32
	Collapsed bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Service struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	Name        string
	IconUrl     pgtype.Text
	IconAssetID pgtype.UUID
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ServiceUrl struct {
	ID        pgtype.UUID
	ServiceID pgtype.UUID
	Label     string
	Kind      string
	Url       string
	SortOrder int32
	IsPrimary bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WidgetCache struct {
	WidgetID  pgtype.UUID
	Status    string
	Data      []byte
	Error     pgtype.Text
	FetchedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WidgetInstance struct {
	ID        pgtype.UUID
	Type      string
	Title     string
	Enabled   bool
	SortOrder int32
	Config    []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
